{% set version = "0.7.0" %}

package:
  name: folium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/folium/folium-{{ version }}.tar.gz
  sha256: 36654b34e3cc09f5779efb715b7377a83875c3ef554d477321921033076db012

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - branca
    - jinja2
    - numpy
    - pandas
    - vincent
    - altair
    - requests

test:
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: 'Make beautiful maps with Leaflet.js and Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
