{% set name = "folium" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/folium-{{ version }}.tar.gz
  sha256: 8ec44697d18f5932e0fdaee8b19da98625de4d0e72cb30ef56f9479f18e11b9f

build:
  number: 0
  skip: True  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - branca >=0.6.0
    - jinja2 >=2.9
    - numpy
    - requests

test:
  imports:
    - folium
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Make beautiful maps with Leaflet.js and Python
  description: |
    folium builds on the data wrangling strengths of the Python ecosystem 
    and the mapping strengths of the leaflet.js library. 
    Manipulate your data in Python, then visualize it in on a Leaflet map via folium.
    folium makes it easy to visualize data that's been manipulated in Python on an interactive leaflet map. 
    It enables both the binding of data to a map for choropleth visualizations 
    as well as passing rich vector/raster/HTML visualizations as markers on the map.
    The library has a number of built-in tilesets from OpenStreetMap, Mapbox, and Stamen, 
    and supports custom tilesets with Mapbox or Cloudmade API keys. 
    folium supports both Image, Video, GeoJSON and TopoJSON overlays.
  doc_url: https://python-visualization.github.io/folium/
  dev_url: https://github.com/python-visualization/folium

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
