{% set version = "0.4.0" %}

package:
  name: folium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/folium/folium-{{ version }}.tar.gz
  sha256: 8130e1d846ec50bd45758e28135834adbd07474c4d98db3316a5f932eb24cb3b

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - branca
    - jinja2
    - numpy
    - pandas
    - vincent
    - altair
    - requests

test:
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: 'Make beautiful maps with Leaflet.js and Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
