{% set version = "0.9.0" %}

package:
  name: folium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/folium/folium-{{ version }}.tar.gz
  sha256: 02054c7a5f898f2593979540b389414c8672d43289991b343511121f3448073a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - branca
    - jinja2
    - numpy
    - pandas
    - vincent
    - altair
    - requests

test:
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: 'Make beautiful maps with Leaflet.js and Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
