{% set version = "0.8.3" %}

package:
  name: folium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/folium/folium-{{ version }}.tar.gz
  sha256: b7a1e907caac6ddaf0614555f58ba9af2ed65356ccc77f6ba6fc3df202d8f146

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - branca
    - jinja2
    - numpy
    - pandas
    - vincent
    - altair
    - requests

test:
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: 'Make beautiful maps with Leaflet.js and Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
