{% set version = "0.12.0" %}

package:
  name: folium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/folium/folium-{{ version }}.tar.gz
  sha256: d45ace0a813ae65f202ce0356eb29c40a5e8fde071e4d6b5be0a89587ebaeab2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - branca >=0.3.0
    - jinja2 >=2.9
    - numpy
    - requests

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - folium

about:
  home: https://github.com/python-visualization/folium
  license: MIT
  license_file: LICENSE.txt
  summary: Make beautiful maps with Leaflet.js and Python

extra:
  recipe-maintainers:
    - ocefpaf
    - BibMartin
