# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "g9Q5Cbov1UPSQekqVQp+njIBnO+8hfwYwm9EdnPiQlTxGlrGHT4KIoMW+rS54M67KtlixGKe8i5uR9NiV8eh5PIF7nNAa4ogJd2dE68XkHlLTKhZFNXjhUMMZTWeAg8hGGuWg64QJVqph9BhboLCHfK/LMfqMBWatHTqwkqTC1gEiRe3F3GPdoCmb2bFxJJHzyHUV2y3a6hntO8WNjxaId+QkBKaf/nUg/+dOuEOHEiunva87KuiobIheLMakIfba0/Dn8u14aHOvEHv7OANhGQUPoXajPaSykVtkPEfHNtcJoZDUC9PifmvD5tx4piK2e5obv4zFzPz1jvTS6+l4xqG47GJi2luUXcZ0srZAo8PiMtJUYi4X+xYqwlgXOcXyrYcQuH8qE45GE2rj3LBrS+7PS+n70DKFp7MbC3WCdDte5PRdTItUoRHTQlbj6K/5uVY++FWirtlvc8XzhY+34SwrFcc+fPeOUXLO/aKr0q49MEA6fjmi0sfa8SSKNUJoLspJqmvl1rocZ59tpgfvKuqFxbqbHJM+iQsgTUkmJcDc1qWeq/el+LD/jOJYnhrp3KBkKSMvXt7jYxRed3FW7i25ss8125nn4q+r4PJdLV2L5BjoeetHIOIEVM/NFSYXPUBClrXhbbakYuMts30jYyGf/bHi4i9iXQfJEeR9vw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
