travis:
  secure:
    BINSTAR_TOKEN: g9Q5Cbov1UPSQekqVQp+njIBnO+8hfwYwm9EdnPiQlTxGlrGHT4KIoMW+rS54M67KtlixGKe8i5uR9NiV8eh5PIF7nNAa4ogJd2dE68XkHlLTKhZFNXjhUMMZTWeAg8hGGuWg64QJVqph9BhboLCHfK/LMfqMBWatHTqwkqTC1gEiRe3F3GPdoCmb2bFxJJHzyHUV2y3a6hntO8WNjxaId+QkBKaf/nUg/+dOuEOHEiunva87KuiobIheLMakIfba0/Dn8u14aHOvEHv7OANhGQUPoXajPaSykVtkPEfHNtcJoZDUC9PifmvD5tx4piK2e5obv4zFzPz1jvTS6+l4xqG47GJi2luUXcZ0srZAo8PiMtJUYi4X+xYqwlgXOcXyrYcQuH8qE45GE2rj3LBrS+7PS+n70DKFp7MbC3WCdDte5PRdTItUoRHTQlbj6K/5uVY++FWirtlvc8XzhY+34SwrFcc+fPeOUXLO/aKr0q49MEA6fjmi0sfa8SSKNUJoLspJqmvl1rocZ59tpgfvKuqFxbqbHJM+iQsgTUkmJcDc1qWeq/el+LD/jOJYnhrp3KBkKSMvXt7jYxRed3FW7i25ss8125nn4q+r4PJdLV2L5BjoeetHIOIEVM/NFSYXPUBClrXhbbakYuMts30jYyGf/bHi4i9iXQfJEeR9vw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
