travis:
  secure:
    BINSTAR_TOKEN: j9V2y3YiK3Is46dGfQ002zc5M0ZCrvSbGvM/RvyPrnHmSj9V/g6YXGDoaIgQPn61tcqkMKutNOtu5DQFRJlsHkwes3GHL+END9fj8llReRHwTsY/sL0B+sHSqJhcx0na9IlnS34Ga6ukx+I6t+C//tJmRiFCXwQJhabaU2Q+l3wXFg8oFb9/fFwX7eKYQWiYItmEzNlVG1q7IVcIPFKMwds8AlCIWFTdFpE7FHKnNwa0ibSE4y0bWVAUN14Gk3ewQjmYHesq+6TvpW6pYPb9Ny4HGdh1Hpp0/S3Xg2y49YDagSeWw0OQ4paez+L8EmfSDOwd4USjlLRELdbW9dlqxfBsnGFIMyyX1hRHWcLjNE9owlh6mXzjqzH7ldflmkAnXG1A7VHgJRYpH27SkEHMjOWFWluDsqUJ2fB53z31Le7YaI7EcJ+UlAAlHs0YvbHeAmGlri8FkxSKSX5nV593mM9z4ZHFQQN+/qfOhf9dvn9t6Asf55tj0L1aHdyb51I6NkehsiUFrFavyqDEyN5vesHNiPdKbnlcRDGUfzhBON0vLUkMwbN7DLoknQ5jwhXUfT8bUjLxOksrFh0w72zgXoWkEsZ9SvS3idsfYoiXwyyYme6sK32U/oUdPxLBtRsBY4DNAb9wi0aRnkpJ2BdQ1UMvnKyIBo8CkhYVSJP/YCo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
