travis:
  secure:
    BINSTAR_TOKEN: HmHlXQMPFEEjGksHplFSxTW+HgZOLrT7izJ1SJS0740Ch3RCHcGj6duvWEvej+9VRJpoEHW+wgu29vLZlch3OorJLS8hpNAPQ4dc0eX4yI9CrTvhvFAidkFtef4I9VCFElYEM2E+pupqr97eWMYfumrQqP9axdEQmUUHLcDaJQw33RtB+ysbr6dojWgDep7Yz4gF+I8gSLd8nFXa/f20OoyUej6UN76zKUfluxiDOgUZYY9psOjFz9F0JmbalvX0bqlEvvqzNHgmpQhpfM7sZw7VBR3gsTi2PlMzOV8F7XfroSm8idYLZiPTY8HpXYVBV0xSkIy4a4JEQ3kEzsSukSvGcozP1F33Q2LqI0CVkon7HnnPnsOPv4pkq+jk7eHeSWAb9rliTRCVTSpGrxvdlzQdhwcpkySVU4o3jxgEfUVK2pM/D6O/sW2biMxVsguceSSBxG4chJSg/HRkzhOqtF3+8nqwSS3+nXnX6sPribXznVgT0d9cS31XCBSgd4RQNiSqRg737zuU1RS091bdcVbWV1Hu6Gqh06uE0s+M67OBURWSPthGRPv43C9sc7G/C+UlJW3+EG6OZEqyeKCiqNh7O1RQ2ySOz36ElKsiZWuXySXUivUfwhVmPkpsxu4yvmwhUKC1CGDjwHEVVGFeWtimSZS8CgXesGcsO4xo45Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
