travis:
  secure:
    BINSTAR_TOKEN: DYNMNpEhTwKLW6wRjwubDQ4CAZ8ny2qn0dSYKSqQ2eomQK2mefdxNX7I6OT989xawT8j5jg5H5xd5SdXijqH78fASx2NUq/+ueeFAfpKu/F8nLqrhpVSEFLfbPg5e4cSzqsmWuAt/djcPzm+TlUmTRXsdNmjJvOt2Ztiy1QTkdXaNy3aX+dLBn9l9Pyzwqbwlos+uwLM+jSoLsxw8F14y+yAvb8uZnPenOxTYcGHcKvMk6ji1Ja+s/TNUpvW2m7l9n0eJPwV9tfAk3twxFrW5kvgFHZ/9hW1X1QEvEikZmZ1HhJC95IXdfy0d7qXijbkyyQ+Ex6cwj+Iv1hP9228mAjvJk2J5OKL4dyQqD4NeO4EARPo9c7uDuO8KZH16fMy/jurAZxfrBTRAydy1PKg+2vYWKNnvslBggI+KRYAH5IY01tkaQQsXzYgTmE2kt9GXZHtTv+ptd9DLjbRiXtspYRCXbPY+rJhhVnWCY+2s0x+D6jtf0TCW8I6858AGHGX9PBAmbFB9A7tKihp8SOqC/UUKqzvi50uP8suTt3/zelmSxcekyJzMmtzHMyw3WJZS8dk6I1i2WskNoNXFYBuaWOcjhWBl/kh9FYNIIfZ4j6ZxicihSgoqA1VvteQnM62/UDfFC+6coYCmy3kuJ36mpq1avOFBmN8RCV4zcRsCxE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
